name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pgmq:
        image: tembo.docker.scarf.sh/tembo/pg17-pgmq:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build pgmq-rest Docker image
        run: docker build -t pgmq-rest .

      - name: Run pgmq-rest container
        run: |
          docker run -d \
            --name pgmq-rest \
            --link pgmq:postgres \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e DB_NAME=postgres \
            -e DB_POOL_SIZE=20 \
            pgmq-rest

      - name: Wait for pgmq-rest to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "pgmq-rest is ready"
              exit 0
            fi
            echo "Waiting for pgmq-rest to be ready..."
            sleep 1
          done
          echo "pgmq-rest failed to start"
          exit 1

      - name: Run tests
        run: |
          DB_HOST=postgres \
          DB_PORT=5432 \
          DB_USER=postgres \
          DB_PASSWORD=postgres \
          DB_NAME=postgres \
          DB_POOL_SIZE=20 \
          bun test
